### Rule (compile): a single `.c` -> `.o` (gcc)
$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@) && echo + CXX $<
	@$(CC) $(CFLAGS) $(EXTRAFLAG) -c -o $@ $(realpath $<)

### Rule (compile): a single `.S` -> `.o` (gcc, which calls as)
$(BUILD)/%.o: %.S
	@mkdir -p $(dir $@) && echo + AS $<
	@$(AS) $(ASFLAGS) -c -o $@ $(realpath $<)

### Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(addsuffix .d, $(basename $(OBJS)))